// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjbwfbepozwojzvmzyyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqYndmYmVwb3p3b2p6dm16eXlsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxOTk4MDEsImV4cCI6MjA2ODc3NTgwMX0.glEJEDuQjPHQEgRkTKZgqwcwaWwBqlDVlcBplraIy4w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});